#!/usr/bin/env python3

import os
import argparse
from metis.Utils import make_tarball

def make(output, cmssw_base=None, skip_root=False, exclude_patterns=None, extra_paths=[], use_bz2_algo=False,use_xz_algo=False,xz_level=None):

    extra = {}
    if cmssw_base:
        if not os.path.exists(cmssw_base):
            raise Exception("That cmssw base directory does not exist!")
            cmssw_base = os.path.abspath(cmssw_base)

    extra = {
            "override_cmssw_base": cmssw_base,
            "exclude_root_files": skip_root,
            "exclude_patterns": exclude_patterns,
            "extra_paths": extra_paths,
            "use_bz2": use_bz2_algo,
            "use_xz": use_xz_algo,
            "xz_level": xz_level,
            }

    print("[mtarfile] Making tarfile")
    if not use_xz_algo:
        print("[mtarfile] Hey, uh, so I saw you're not using the --xz flag. I "
                "recommend using it to switch to the xz algorithm when tarring. By default, "
                "it can shrink the file size by ~20-30% for no extra cost in time. If you "
                "plan to submit many jobs, please additionally use --xz_level 9 and wait a "
                "couple of minutes for another ~5-10%.")
    if skip_root:
        print("[mtarfile] Skipping root files")
    if exclude_patterns:
        print("[mtarfile] Skipping paths/files matching any of {}".format(exclude_patterns))
    make_tarball(output, **extra)
    print("[mtarfile] Made {0:.1f}MB tarfile: {1}".format(1.e-6*os.path.getsize(output), output))

    return True

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("output", help="name of output tar file")
    parser.add_argument("-c", "--cmssw", help="CMSSW_BASE directory, default is $CMSSW_BASE", default=None)
    parser.add_argument("-n", "--norootfiles", help="don't tar up root files", action="store_true")
    parser.add_argument("-e", "--extrapaths", help="extra files/dirs to include in tarfile", nargs="+")
    parser.add_argument("-x", "--excludepatterns", help="str to match to exclude in tarfile (can have multiple, if the pattern has a *, it is matched, otherwise we check for string containment)", default=[], nargs="*")
    parser.add_argument("-b", "--bz2", help="use bz2 algorithm", action="store_true")
    parser.add_argument("-X", "--xz", help="use xz algorithm", action="store_true")
    parser.add_argument("-l", "--xz_level", help="xz compression level (0 to 9)", default=None)

    args = parser.parse_args()

    make(args.output, args.cmssw, args.norootfiles, args.excludepatterns, args.extrapaths, args.bz2, args.xz, args.xz_level)
